FROM python:3.11-slim

WORKDIR /app

COPY discovery/requirements.txt discovery/requirements.txt

# use --no-cache-dir in production
RUN echo "STARTING DISCOVERY SERVICE..." && \
    pip install -r discovery/requirements.txt

COPY discovery discovery
COPY config.json config.json
COPY contract contract

WORKDIR /app/discovery/src

ENTRYPOINT ["uvicorn", "main:app", "--port", "7000", \
    "--host", "0.0.0.0", \
    "--reload", \
    "--forwarded-allow-ips", "*"]

EXPOSE 7000
