FROM eclipse-temurin:11-jdk-alpine as build

WORKDIR /app

COPY mvnw .

RUN sed -i 's/\r$//' mvnw

COPY .mvn .mvn
COPY pom.xml .
COPY src src

RUN ./mvnw install -DskipTests

FROM eclipse-temurin:11-jdk-alpine
COPY --from=build app/target/did-0.0.1-SNAPSHOT.jar did3.jar
CMD ["java", "-Dspring.profiles.active=docker-sbip,issuer", "-jar", "/did3.jar"]
EXPOSE 9090
