# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schema.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cschema.proto\"\'\n\x08Resource\x12\x0b\n\x03\x63pu\x18\x01 \x01(\x05\x12\x0e\n\x06memory\x18\x02 \x01(\x05\"\x89\x01\n\x04Task\x12\n\n\x02id\x18\x01 \x01(\t\x12\x14\n\x0c\x63ontainerRef\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x1b\n\x08resource\x18\x04 \x01(\x0b\x32\t.Resource\x12\x0f\n\x07runtime\x18\x05 \x01(\t\x12\x0e\n\x06useGpu\x18\x06 \x01(\x08\x12\x10\n\x08gpuCount\x18\x07 \x01(\x05\"\x9e\x01\n\nTaskResult\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x1b\n\x08resource\x18\x03 \x01(\x0b\x32\t.Resource\x12\"\n\x1atransaction_start_datetime\x18\x04 \x01(\x05\x12 \n\x18transaction_end_datetime\x18\x05 \x01(\x05\x12\x10\n\x08\x64uration\x18\x06 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schema_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_RESOURCE']._serialized_start=16
  _globals['_RESOURCE']._serialized_end=55
  _globals['_TASK']._serialized_start=58
  _globals['_TASK']._serialized_end=195
  _globals['_TASKRESULT']._serialized_start=198
  _globals['_TASKRESULT']._serialized_end=356
# @@protoc_insertion_point(module_scope)
